[tool.poetry]
name = "e2e"
version = "0.1.0"
description = ""
authors = ["Magnus Glasder <mglasder@ethz.ch>"]
readme = "README.md"
packages = [{include = "e2e"}]

[tool.black]
line-length = 120
target-version = ["py39"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^3.3.2"
lightning = "^2.0.2"
hornets-nest= {path = "libs/hornets-nest-2022.6.1.tar.gz"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
